// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4F_HW71K_gpjX5hyrn4isyuEUfSOFTOk',
    appId: '1:675635348816:android:95047e40921d82d6bcd855',
    messagingSenderId: '675635348816',
    projectId: 'madadwe-4781a',
    storageBucket: 'madadwe-4781a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6syav78kGGF-2V490-l178Sd8ryhNcls',
    appId: '1:675635348816:ios:dc82101ca2235b52bcd855',
    messagingSenderId: '675635348816',
    projectId: 'madadwe-4781a',
    storageBucket: 'madadwe-4781a.appspot.com',
    androidClientId: '675635348816-qsrapb4uqb7mhc67m874lujfcp5lfad8.apps.googleusercontent.com',
    iosClientId: '675635348816-ufqqqeldtq6gfpcdn3kmfu7aiqd412p2.apps.googleusercontent.com',
    iosBundleId: 'com.example.madadFinal',
  );
}
